let fileType = {
    'txt': 'txt',
    'xls': 'excel',
    'xlsx': 'excel',
    'csv': 'excel',
    'ppt': 'ppt',
    'pptx': 'ppt',
    'mp4': 'video',
    'avi': 'video',
    'rmvb': 'video',
    'wmv': 'video',
    'mkv': 'video',
    'flv': 'video',
    'mov': 'video',
    'webm': 'video',
    'png': 'image',
    'jpg': 'image',
    'jpeg': 'image',
    'gif': 'image',
    'bmp': 'image',
    'icon': 'image',
    'zip': 'zip',
    'rar': 'zip',
    '7z': 'zip',
    'tar': 'zip',
    'gz': 'zip',
    'tar.gz': 'zip',
    'iso': 'zip',
    'pdf': 'pdf',
    'doc': 'word',
    'docx': 'word',
    'mp3': 'audio',
    'aac': 'audio',
    'wav': 'audio',
    'flac': 'audio',
    'url': 'url',
    'html': 'url'
}

export default fileType